trigger:
- azurepoc

pool:
  name: Default

strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Create virtual environment
      python -m venv venv
      
      # Activate the virtual environment
      .\venv\Scripts\activate
      
      # Upgrade pip and install dependencies
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      
      # Install testing tools
      pip install pytest pytest-azurepipelines selenium
      
      # Run the tests
      pytest ui-systests/webapp/marketing/test_azure_poc.py --maxfail=5 --disable-warnings -q
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Set up environment and run tests'
